title: Facilitating Reproducibility and Collaboration with Literate Programming
description: e-Science Symposium 2018, University of Massachusetts Medical School, Worcester MA - April 5, 2018
author: Harrison Dekker
theme: jekyll-theme-minimal